schema: schema.graphql
documents: ./graphql/**/*.graphql
projects:
  vinteadClone:
    schema: schema.graphql
    documents: ./graphql/**/*.graphql
    extensions:
      endpoints:
        default:
          url: http://localhost:3001/graphql
          headers:
            Authorization: Bearer ${AUTH_TOKEN}
