schema: http://localhost:3001/graphql
documents: '**/*.graphql'
projects:
  vinteadClone:
    schema: http://localhost:3001/graphql
    documents: '**/*.graphql'
    extensions:
      endpoints:
        default:
          url: http://localhost:3001/graphql
          headers:
            Authorization: Bearer ${AUTH_TOKEN}
